# Generated by Django 5.0.2 on 2024-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsnapapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_seats',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
