# Generated by Django 5.0.2 on 2024-03-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsnapapp', '0002_remove_booking_booked_seats_booking_booked_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_seats',
            field=models.ManyToManyField(to='showsnapapp.seat'),
        ),
    ]
