# Generated by Django 5.0.2 on 2024-03-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsnapapp', '0003_remove_booking_booked_seats_booking_booked_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=50)),
                ('bkd_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showsnapapp.customer')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showsnapapp.screening')),
            ],
        ),
    ]
